apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: wp-mysql-005
  namespace: k8a
spec:
  version: "5.7.25"
  #  version: "8.0.14"
  #configSource:
  #  configMap:
  #    name: mysql-config-005
  storageType: Durable
  storage:
    storageClassName: "nfs-client"
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
  monitor:
    agent: prometheus.io/builtin
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
  terminationPolicy: WipeOut
