apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-005
  namespace: k8a
data:
  db_conf.cnf: |-
    [mysqld]
    default_authentication_plugin = mysql_native_password
    skip-name-resolve
    max_connections = 300
    max_user_connections = 300
    myisam_sort_buffer_size = 64M

    key_buffer_size = 256M
    read_buffer_size = 1M
    table_open_cache = 15000
    thread_cache_size = 384

    wait_timeout = 300
    connect_timeout = 10
    interactive_timeout = 7000

    tmp_table_size = 256M
    max_heap_table_size = 256M
    innodb_buffer_pool_size = 1G
    thread_cache_size = 100

    join_buffer_size = 2M
    read_buffer_size = 2M
    sort_buffer_size = 3M

    max_allowed_packet = 32M
    max_connect_errors = 1000

    innodb-flush-log-at-trx-commit = 2

    ### this configuration will purge flushed binary logs over 7 days old
    binlog_expire_logs_seconds = 604800
